source 'https://github.com/CocoaPods/Specs.git'

target 'IpHelper', :exclusive => true do
  pod "IpHelper", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "IpHelper", :path => "../"

  
end
